name: Publish Python release

on:
  push:

jobs:
  macos-aarch64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python --version
      - name: Set up Rust with apple target
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: aarch64-apple-darwin
      - name: Publish wheel
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        with:
          working-directory: random-partition-py
          target: aarch64-unknown-linux-gnu
          command: build
          args: --release --target aarch64-apple-darwin -i python
