name: Publish Python release

on:
  push:

jobs:
  # build for basic ubuntu, macos, windows
  manylinux-x64_64-win-macos:
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
      steps:
        - uses: actions/checkout@v3
        - uses: dtolnay/rust-toolchain@stable
        - name: Publish wheel
          uses: PyO3/maturin-action@v1
          env:
            MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          with:
            working-directory: random-partition-py
            command: build
            args: --release

  # Apparently needed for Docker on Apple M1? pola-rs does this in their action
  manylinux-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish wheel
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        with:
          working-directory: random-partition-py
          target: aarch64-unknown-linux-gnu
          command: build
          args: --release

  macos-aarch64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust with apple target
        uses: dtolnay/rust-toolchain@master
        with:
          targets: aarch64-apple-darwin
      - name: Publish wheel
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        with:
          working-directory: random-partition-py
          target: aarch64-unknown-linux-gnu
          command: build
          args: --release --target aarch64-apple-darwin
